import assert from 'node:assert/strict';
import fs from 'node:fs';
import {codexCatalog,claudeSettings,openCodeConfig,efforts} from './adapters.mjs';
const catalog=JSON.parse(fs.readFileSync(new URL('./seed.json',import.meta.url)));
const templates={models:[{slug:'gpt-5.6-sol',base_instructions:'Keep this transport prompt',shell_type:'shell_command',default_reasoning_level:'medium'}, {slug:'local/model',base_instructions:'Local'}]};
const cx=codexCatalog(catalog,templates,['local/model']);
assert.equal(cx.models.length,12);
assert.equal(cx.models.at(-1).slug,'local/model');
assert.equal(cx.models[0].base_instructions,'Keep this transport prompt');
let swe=cx.models.find(m=>m.slug==='devin/swe-2');
assert.equal(swe.context_window,262000);assert.deepEqual(swe.input_modalities,['text','image']);
assert.deepEqual(swe.supported_reasoning_levels.map(x=>x.effort),['medium','high','max']);
assert.deepEqual(efforts(catalog.models.find(m=>m.id==='opencode-go/deepseek-v4.1-flash')),['low','high','max']);
const old={model:'devin/swe-2',permissions:{allow:['Read']},modelSettings:{custom:{effortLevel:'low'}}};
const cc=claudeSettings(catalog,old);
assert.equal(cc.model,'devin/swe-2');assert.deepEqual(cc.permissions,old.permissions);assert.deepEqual(cc.modelSettings,old.modelSettings);assert.equal(cc.modelPicker.options.length,11);assert.equal(old.modelPicker,undefined);
const oc=openCodeConfig(catalog,'http://127.0.0.1:8317','cpa-codex/opencode-go/muse-spark-1.3-contributor');
assert.equal(oc.model,'cpa-codex/opencode-go/muse-spark-1.3-contributor');
assert.equal(oc.provider['cpa-chat'].models['devin/swe-2'].limit.output,128000);
assert.deepEqual(oc.provider['cpa-chat'].models['devin/swe-2'].variants.low,{disabled:true});
assert.deepEqual(oc.provider['cpa-chat'].models['devin/swe-2'].variants.max,{reasoningEffort:'max'});
const extra=structuredClone(catalog);extra.models.push({...structuredClone(catalog.models[0]),id:'test-added'});
assert.equal(codexCatalog(extra,templates).models.length,12);
assert.equal(claudeSettings(extra,cc).modelPicker.options.length,12);
assert.equal(Object.values(openCodeConfig(extra,'http://localhost').provider).reduce((n,p)=>n+Object.keys(p.models).length,0),12);
assert.equal(claudeSettings(catalog,claudeSettings(extra,cc)).modelPicker.options.length,11);
console.log('Adapter tests passed: preservation, metadata/effort mapping, nested IDs, add/remove propagation.');
const {openCodeV2Config}=await import('./adapters.mjs');
const oldV2={model:'cpa-codex/opencode-go/muse-spark-1.3-contributor',providers:{'cpa-codex':{settings:{apiKey:'{env:CPA_API_KEY}',baseURL:'http://127.0.0.1:8317/v1'},models:{'opencode-go/muse-spark-1.3-contributor':{}}},other:{name:'untouched'}},permissions:{edit:'ask'}};
const v2=openCodeV2Config(catalog,oldV2,'http://127.0.0.1:8317');
assert.equal(v2.model,oldV2.model);assert.deepEqual(v2.providers.other,oldV2.providers.other);assert.deepEqual(v2.permissions,oldV2.permissions);
assert.deepEqual(v2.providers['cpa-chat'].models['devin/swe-2'].variants.map(x=>x.id),['medium','high','max']);
assert.deepEqual(v2.providers['cpa-chat'].models['devin/swe-2'].variants[2].body,{reasoning_effort:'max'});
assert.deepEqual(v2.providers['cpa-codex'].models['gpt-6-astra'].cost[1].tier,{type:'context',size:272000});
console.log('OpenCode v2 adapter checks passed.');
